name: myoro_matchup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  myoro_flutter_library:
    path: ../myoro_flutter_library
    # git:
    #   url: git@github.com:antonkoetzler/myoro_flutter_library
  faker: 2.1.0
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.2
  kiwi: ^5.0.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
